server:
  port: 8080

spring:
  application:
    name: API-GATE-WAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
          - Path=/micro/**

